version: '3.8'

services:
    database:
        container_name: database
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: chat_app
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        ports:
            - '3306:3306'
        volumes:
            - ./docker/mysql:/var/lib/mysql

    php:
        container_name: php
        build:
            context: ./docker/php
        ports:
            - '9000:9000'
        volumes:
            - .:/var/www/app
        depends_on:
            - database

    nginx:
        container_name: nginx
        image: nginx:1.22-alpine
        ports:
            - '80:80'
        volumes:
            - .:/var/www/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - database

    mercure:
        image: dunglas/mercure
        restart: unless-stopped
        environment:
            SERVER_NAME: ':3000'
            MERCURE_PUBLISHER_JWT_KEY: '7d2b79257e5deb260e4590b099bb81f9'
            MERCURE_SUBSCRIBER_JWT_KEY: '7d2b79257e5deb260e4590b099bb81f9'
            # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
            #            MERCURE_EXTRA_DIRECTIVES: |
            #                cors_origins http://localhost
            # Comment the following line to disable the development mode
        command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
        ports:
            - '3000:3000'
            - '3001:443'
        volumes:
            - mercure_data:/data
            - mercure_config:/config

volumes:
    ###> symfony/mercure-bundle ###
    mercure_data:
    mercure_config: ###< symfony/mercure-bundle ###
