league_oauth2_server:
    authorization_server:
        # Full path to the private key file.
        # How to generate a private key: https://oauth2.thephpleague.com/installation/#generating-public-and-private-keys
        private_key: '%env(resolve:OAUTH_PRIVATE_KEY)%'

        # Passphrase of the private key, if any
        private_key_passphrase: '%env(resolve:OAUTH_PASSPHRASE)%'

        # The plain string or the ascii safe string used to create a Defuse\Crypto\Key to be used as an encryption key.
        # How to generate an encryption key: https://oauth2.thephpleague.com/installation/#string-password
        encryption_key: '%env(resolve:OAUTH_ENCRYPTION_KEY)%'

        # The type of value of 'encryption_key'
        encryption_key_type: plain # One of "plain"; "defuse"

        # How long the issued access token should be valid for.
        # The value should be a valid interval: http://php.net/manual/en/dateinterval.construct.php#refsect1-dateinterval.construct-parameters
        access_token_ttl: PT1H

        # How long the issued refresh token should be valid for.
        # The value should be a valid interval: http://php.net/manual/en/dateinterval.construct.php#refsect1-dateinterval.construct-parameters
        refresh_token_ttl: P1M

        # How long the issued auth code should be valid for.
        # The value should be a valid interval: http://php.net/manual/en/dateinterval.construct.php#refsect1-dateinterval.construct-parameters
        auth_code_ttl: PT10M

        enable_client_credentials_grant: false
        enable_password_grant: true
        enable_refresh_token_grant: true
        enable_auth_code_grant: true
        require_code_challenge_for_public_clients: true
        persist_access_token: true

    resource_server:
        public_key: '%env(resolve:OAUTH_PUBLIC_KEY)%'

    scopes:
        # Scopes that you wish to utilize in your application.
        # This should be a simple array of strings.
        available: [ 'all' ]

        # Scopes that will be assigned when no scope given.
        # This should be a simple array of strings.
        default: [ 'all' ]

    # Configures different persistence methods that can be used by the bundle for saving client and token data.
    # Only one persistence method can be configured at a time.
    persistence:
        doctrine: null

when@test:
    league_oauth2_server:
        persistence:
            in_memory: null
